imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: en}
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        name: %session_name%
        cookie_lifetime: %cookie_lifetime%
        cookie_httponly: true
    fragments:       ~
    http_method_override: true

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        media_domain: %media_domain%
        google_analytics_code: %google_analytics_code%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ EVTIntranetBundle, EVTEAEBundle ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    auth_mode: login
    encryption: tls
    port:       587
    logging:    %kernel.debug%

evteae:
    aws:
        key: %aws_key%
        secret: %aws_secret%
        region: eu-west-1
    api_keys: %api_keys%

# Doctrine Configuration
doctrine:
    dbal:
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                metadata_cache_driver: redis
                query_cache_driver: redis
                connection: default
                mappings:
                    EVTIntranetBundle: ~
                    EVTDIYBundle: ~

# REDIS
snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: %redis_default%
        auth:
            type: predis
            alias: auth
            dsn: %redis_default%
        session:
            type: predis
            alias: session
            dsn: %redis_session%
    session:
        client: session
        prefix: evt_session
    doctrine:
        metadata_cache:
            client: default
            entity_manager: [default]
            namespace: "evt:ae:meta:"
        query_cache:
            client: default
            entity_manager: [default]
            namespace: "evt:ae:query:"

fos_rest:
    routing_loader:
        default_format:       json
        include_format:       false
    view:
        view_response_listener: force
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        formats:
            json: true
            xml: false
            rss: false
        jsonp_handler: ~
    body_listener:
        decoders:
            json: fos_rest.decoder.json
    param_fetcher_listener: true
    access_denied_listener:
        # all requests using the 'json' format will return a 403 on an access denied violation
        json: true
    format_listener:
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: false }
            - { path: '^/', priorities: ['html'], fallback_format: html, prefer_extension: false }
