evt_intranet:
    resource: "@EVTIntranetBundle/Controller/"
    type:     annotation
    prefix:   /

evt_hook:
    resource: "@EVTHookBundle/Controller/"
    type:     annotation
    prefix:   /hooks/

login_check:
    path: /login_check

logout:
    path: /logout