evt_ae:
    resource: "@EVTEAEBundle/Controller/"
    type:     annotation
    prefix:   /

evt_intranet:
    resource: "@EVTIntranetBundle/Controller/"
    type:     annotation
    prefix:   /manager/

evt_hook:
    resource: "@EVTHookBundle/Controller/"
    type:     annotation
    prefix:   /hooks/

login_check:
    path: /manager/login_check

logout:
    path: /manager/logout