evt_ae:
    resource: "@EVTEAEBundle/Controller/"
    type:     annotation
    prefix:   /

evt_intranet:
    resource: "@EVTIntranetBundle/Controller/"
    type:     annotation
    prefix:   /{_role}/
    defaults: { _role: manager }
    requirements:
        _role: manager|employee

evt_hook:
    resource: "@EVTHookBundle/Controller/"
    type:     annotation
    prefix:   /hooks/

login_check:
    path: /manager/login_check

logout:
    path: /manager/logout