evt_intranet:
    resource: "@EVTIntranetBundle/Controller/"
    type:     annotation
    prefix:   /

evt_hook:
    resource: "@EVTHookBundle/Controller/"
    type:     annotation
    prefix:   /hooks/

