security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        EVT\IntranetBundle\Security\EVTUser: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        api_key:
            id: evt.api_key.user_provider

        evt_core:
            id: evt_user_provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        apikey_secured_area:
            pattern: ^/hooks
            stateless: true
            anonymous: false
            simple_preauth:
                authenticator: evt.api_key.authenticator
        login:
            pattern:  ^/login$
            security: false

        resetpassword:
            pattern:  ^/resetpassword$
            security: false

        admin_secured_area:
            pattern:   ^/(manager|employee)
            anonymous: false
            form_login:
                login_path: login
                default_target_path: /manager
                check_path: /manager/login_check
            provider: evt_core
            remember_me:
                key:      "%secret%"
                lifetime: %cookie_lifetime%
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            logout:
                path:    /manager/logout
                target:  /login

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
