parameters:
#    evtdiy.example.class: EVT\DIYBundle\Example

services:
    evt.diy.showroom.manager:
        class: EVT\DIYBundle\Model\Manager\ShowroomManager
        arguments:
          - @evt.emd.client.showroom
          - @evt.diy.showroom.mapper
          - @doctrine.orm.entity_manager

    evt.diy.showroom.mapper:
        class: EVT\DIYBundle\Model\Mapper\ShowroomMapper
