parameters:
#    evtdiy.example.class: EVT\DIYBundle\Example

services:
    evt.diy.showroom.manager:
        class: EVT\DIYBundle\Model\Manager\ShowroomManager
        arguments:
          - @evt.emd.client.showroom
          - @evt.diy.showroom.mapper
          - @doctrine.orm.entity_manager
          - @evt.core.client

    evt.diy.showroom.mapper:
        class: EVT\DIYBundle\Model\Mapper\ShowroomMapper

    evt.aws.s3.client:
        class: Aws\S3\S3Client
        factory_class: Aws\S3\S3Client
        factory_method: 'factory'
        arguments:
            -
                key: %aws_key%
                secret: %aws_secret%
                region: %aws_region%

    evt.diy.uploader:
        class: EVT\DIYBundle\Services\Storage\ImageUploader
        arguments:
         - @evt_img_showrooms_filesystem