parameters:
#    evteae.example.class: EVT\EAEBundle\Example

services:
    evt.mailer:
        class: EVT\EAEBundle\Communication\Email\Emailer
        arguments: [@mailer, @css_to_inline_email_converter]

    evt.api_key.user_provider:
        class: EVT\EAEBundle\Security\ApiKeyUserProvider
        arguments: [%evteae.api_keys%]

    evt.api_key.authenticator:
        class:     EVT\EAEBundle\Security\ApiKeyAuthenticator
        arguments: [@evt.api_key.user_provider]
