parameters:
#    evteae.example.class: EVT\EAEBundle\Example

services:
    aws.ses:
        class: Aws\Ses\SesClient
        arguments: [%aws_key%, %aws_secret%, %aws_region%]

    evt.mailer.base_aws_mailer:
        class: EVT\EAE\Communication\Mailer\AWSWelcomeMailer
        arguments: [@aws.ses, []]

    evt.mailer.aws_welcome:
        class: EVT\EAEBundle\Factory\AWSMailerFactory
        arguments: [@twig, @translator, @evt.mailer.base_aws_mailer]
